# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Secrets
      run: |
          cat << EOF > secrets.json
          { "discordAPI": "$TOKEN", "giphyAPI": "$giphyAPI" }
          EOF
      env:
        TOKEN: ${{ secrets.DISCORD_TOKEN }}
        giphyAPI: ${{ secrets.GIPHY }}
    - name: Firebase API
      run: gdown $FIREBASE_PRIVATE_KEY --fuzzy
      env:
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
    - name: Run Discord
      run: |
        python main.py&
